import re

# All unique job titles sourced from from_values.txt
JOB_TITLES = [
    'Software Engineer', 'Systems Engineer', 'Software Developer',
    'Senior Software Engineer', 'Programmer', 'Programmer Analyst',
    'Web Developer', 'Systems Administrator', 'Network Engineer',
    'Systems Analyst', 'Software Engineer Intern',
    'Associate Software Engineer', 'Web Designer', 'Developer',
    'Software Engineering Intern', 'Network Administrator',
    'Technical Recruiter', 'Database Administrator',
    'Quality Assurance Analyst', 'Quality Assurance Engineer',
    'Application Developer', 'Business Systems Analyst', 'Java Developer',
    'Technology Analyst', 'Software Engineer II', 'Software Consultant',
    'Software Development Engineer', 'Senior Programmer',
    'Technical Staff Member', 'Software Developer Intern', 'Webmaster',
    'Quality Assurance Tester', 'Senior Systems Engineer',
    'Information Technology Specialist', 'Junior Software Engineer',
    'Associate Systems Engineer', 'Software Development Intern',
    'Software Quality Assurance Engineer',
    'Test Software Development Engineer', 'Senior Business Analyst',
    'Senior Systems Administrator', 'Software Development Engineer Intern',
    'Technical Consultant', 'Network Technician', '.NET Developer',
    'Information Technology Project Manager', 'Software Intern',
    'Network Analyst', 'Oracle Database Administrator',
    'Senior Programmer Analyst', 'Database Developer',
    'Technical Support Engineer', 'Software Engineer III',
    'Senior Web Developer', 'Technical Lead', 'Solution Architect',
    'Senior Systems Analyst', 'Help Desk Technician',
    'Technical Support Specialist', 'Scrum Master',
    'Information Technology Analyst', 'Senior Java Developer',
    'Computer Technician', 'Software Test Engineer', 'Support Analyst',
    'Systems Programmer', 'J2EE Developer', 'Software Design Engineer',
    'Junior Software Developer', 'User Experience Designer',
    'Information Technology Consultant', 'Support Engineer',
    'Assistant Systems Engineer', 'Junior Programmer',
    'Information Technology Recruiter', 'Software Architect',
    'Junior Systems Administrator', 'Junior Web Developer',
    'Information Systems Intern', 'Senior Software Developer',
    'Embedded Software Engineer', 'Desktop Support Technician',
    'Help Desk Analyst', 'Software Analyst', 'ETL Developer',
    'Web Developer Intern', 'Network Specialist',
    'Information Technology Technician', 'Lead Software Engineer',
    'Web Programmer', 'Technical Architect', 'Senior Developer',
    'Firmware Engineer', 'Interaction Designer', 'Chief Architect',
    'Application Analyst', 'SAP Consultant', 'Programmer Trainee Analyst',
    'Software Development Manager', 'Associate Software Developer',
    'Principal Software Engineer', 'Software Development Engineer II',
    'Web Application Developer', 'Front End Developer',
    'Unix Systems Administrator', 'Information Technology Support', 'Test Lead',
    'Security Engineer', 'Application Programmer',
    'Senior Quality Assurance Analyst', 'Systems Engineer II',
    'Associate Systems Analyst', 'Associate Project Manager',
    'Senior Network Engineer', 'Technical Project Manager',
    'Associate Programmer Analyst', 'Test Analyst', 'UX Designer',
    'Technology Consultant', 'Module Lead', 'Associate Programmer',
    'Technical Support Analyst', 'Data Scientist',
    'Business Intelligence Developer', 'Information Technology Intern',
    'Business Analyst Consultant', 'Developer Intern',
    'Information Business Technology Analyst',
    'Associate Business Systems Analyst', 'User Interface Designer',
    'User Interface Developer', 'SharePoint Developer',
    'Trainee Software Engineer', 'Solution Consultant', 'Computer Engineer',
    'Software Tester', 'SQL Server Database Administrator',
    'Staff Software Engineer', 'Security Analyst', 'Junior Developer',
    'Web Development Intern', 'Information Architect',
    'Systems Software Engineer', 'Desktop Support Specialist',
    'Lead Programmer', 'Application Architect',
    'Information Technology Professional', 'Solution Engineer',
    'Technical Account Manager', 'Systems Architect',
    'Local Area Network Administrator', 'Network Support Engineer',
    'Interactive Developer', 'Web Design Intern', 'Security Consultant',
    'Oracle Developer', 'Programmer Analyst II', 'Implementation Consultant',
    'Senior Technical Writer', 'Systems Trainee Engineer',
    'Technical Program Manager', 'Release Engineer',
    'Senior Staff Software Engineer', 'Senior Network Administrator',
    'Customer Support Engineer', 'Systems Support Specialist',
    'Help Desk Support', 'Technology Head', 'Associate Systems Administrator',
    'iOS Developer', 'Senior Test Engineer', 'Data Architect',
    'Help Desk Specialist', 'Senior Business Systems Analyst',
    'Setup Configuration Analyst', 'Senior Application Developer',
    'Software Quality Assurance Tester', 'Software Quality Engineer',
    'Business Intelligence Consultant',
    'Information Technology Support Technician', 'Systems Analyst II',
    'Assistant Systems Trainee Engineer', 'Lead Developer',
    'Delivery Consultant', 'Information Systems Technician',
    'Software Engineering Manager', 'Associate Developer', 'Game Programmer',
    'PeopleSoft Consultant', 'Customer Success Manager',
    'Senior Software Development Engineer', 'Systems Consultant',
    'Systems Integration Analyst', 'Engineering Senior Director',
    'Senior Quality Assurance Engineer', 'Unix Administrator',
    'Research Programmer', 'Systems Engineer Intern',
    'Associate Quality Assurance Engineer', 'Front End Engineer',
    'Desktop Support Analyst', 'Service Desk Analyst',
    'Senior Database Administrator', 'Software Application Engineer',
    'Salesforce Administrator', 'Technical Genius', 'Informatics Developer',
    'Software Developer II', 'J2EE Consultant', 'Application Consultant',
    'Junior Network Administrator', 'Junior Web Designer',
    'Salesforce Developer', 'Android Developer', 'Senior Application Engineer',
    'Network Engineer II', 'Java Consultant', 'Flash Developer',
    'Information Technology Administrator',
    'Network Operation Center Technician', 'Junior Java Developer',
    'Storage Engineer', 'Trainee Programmer', 'Implementation Analyst',
    'Senior Network Analyst', 'SAP Technical Consultant', 'Database Engineer',
    'Database Programmer', 'Systems Support Analyst',
    'Information Security Analyst', '.NET Consultant', 'Onsite Coordinator',
    'SQL Developer', 'Front End Web Developer',
    'Information Technology Project Coordinator',
    'Quality Assurance Automation Engineer',
    'Software Quality Assurance Analyst', 'Help Desk Administrator',
    'Java Programmer', 'Lead Web Developer', 'Senior Quality Assurance Tester',
    'Enterprise Architect', 'Junior Database Administrator',
    'Technical Associate', 'Storage Administrator',
    'Application Development Manager', 'Network Operation Engineer',
    'Systems Developer', 'Computer Support Specialist',
    'Senior Web Application Developer', 'Data Science Fellow',
    'Software Quality Assurance Intern', 'Assistant Network Administrator',
    'Quality Assurance Lead', 'Intern Programmer', 'Network Support',
    'Product Management Director', 'Oracle Consultant', 'Hadoop Developer',
    'Associate Information Technology Analyst', 'Desktop Administrator',
    'Digital Analyst', 'Associate Network Engineer', 'Web Analyst',
    'Network Support Specialist', 'ERP Consultant',
    'Business Intelligence Architect', 'Delivery Manager',
    'SQL Database Administrator', 'Junior Network Engineer',
    'Senior Technical Consultant', 'Enterprise Account Manager',
    'Database Architect', 'Network Systems Administrator',
    'Infrastructure Engineer', 'Software Trainee',
    'Application Development Specialist', 'Digital Business Analyst',
    'Industrial Technical Engineer', 'SAP FICO Consultant',
    'Functional Analyst', 'Senior Development Head', 'Programmer II',
    'Senior Technical Support Engineer', 'Multimedia Developer',
    'Mobile Developer', 'Build Engineer', 'User Experience Researcher',
    'Search Engine Optimization Specialist', 'Senior Systems Architect',
    'Senior J2EE Developer', 'SAP Basis Consultant', 'Scientific Programmer',
    'Cognos Developer', 'Information Technology Associate', 'Customer Engineer',
    'Network Engineer III', 'Solution Analyst', 'SharePoint Consultant',
    'Computer Support Technician', 'Network Support Technician',
    'Information Technology Support Analyst', 'Embedded Systems Engineer',
    'DevOps Engineer', 'Business Application Analyst',
    'Digital Project Manager', 'Full Stack Web Developer',
    'Senior Interaction Designer', 'Application Support Analyst',
    'Developer Analyst', 'Advanced Software Engineer',
    'Information Technology Support Specialist',
    'Information Technology Architect', 'Senior Principal Consultant',
    'Lead Program Manager', 'PC Support Specialist', 'SAP Basis Administrator',
    'Engineering Vice President', 'Linux Systems Administrator',
    'Software Manager', 'Senior Firmware Engineer',
    'Quality Assurance Consultant', 'Configuration Specialist',
    'Information Technology Systems Administrator', 'Lead Software Developer',
    'SAP Business Intelligence Consultant', 'Data Science Intern',
    'Principal Development Head', 'Oracle Application Developer',
    'Data Warehouse Developer', 'Solution Developer', 'Technical Leader',
    'Test Software Developer', 'ETL Consultant', 'Java Software Engineer',
    'Assistant Systems Administrator', 'Assistant Software Engineer',
    'PC Support Technician', 'Systems Support Technician',
    'Advanced Programmer', 'PHP Developer', 'Junior Quality Assurance Analyst',
    'Senior Technical Analyst', 'User Experience Architect',
    'Pre Sales Engineer', 'Windows Systems Administrator',
    'Senior Software Quality Assurance Engineer', 'Implementation Engineer',
    'Senior Executive Officer Analyst', 'Desktop Technician',
    'Network Security Engineer', 'Systems Administrator II',
    'SAP ABAP Consultant', 'Systems Support Engineer',
    'Network Systems Engineer', 'Senior Support Engineer',
    'Mainframe Developer', 'Reports Developer', 'Server Administrator',
    'SDET Intern', 'Technical Support Associate Engineer',
    'Senior Software Programmer', 'Junior Quality Assurance Engineer',
    'SAP BW Consultant', 'Senior Technical Associate', 'Datastage Developer',
    'Junior Systems Engineer', 'Senior Software Consultant',
    'Technology Architect', 'Senior SharePoint Consultant',
    'Network Consultant', 'Senior Software Architect',
    'Application Developer Intern', 'Student Programmer',
    'Information Technology Programmer', 'Application Support Specialist',
    'Software Support Engineer', 'Drupal Developer', 'Chief Technology Officer',
    'Deployment Technician', 'Oracle Application Consultant',
    'Senior Software Design Engineer', 'Associate Technical Consultant',
    'Programmer Analyst III', 'Database Consultant',
    'Instrument Technician Project Lead', 'Application Sales Representative',
    'Computer Science Tutor', 'Systems Analyst III',
    'Junior Front End Developer', 'Technology Support Specialist',
    'Lead Architect', 'User Experience Design Intern',
    'Account Development Representative', 'Software Specialist',
    'Major Account District Manager', 'Consultant Developer',
    'User Interface Engineer', 'Service Account Manager',
    'Instrument Technician Systems Engineer', 'Data Scientist Intern',
    'Senior Oracle Database Administrator', 'Developer II',
    'Graduate Technical Intern', 'Systems Analyst Intern',
    'Business Objects Developer', 'Senior SQL Server Digital Business Analyst',
    'Service Delivery Manager', 'Quality Assurance Engineer II',
    'Software Design Engineer II', 'Senior Software Analyst',
    'Data Center Technician', 'Senior Solution Consultant',
    'Software Engineering Associate', 'Service Professional Consultant',
    'Visual Data Specialist', 'Lead Application Developer',
    'Enterprise Account Executive', 'Search Engine Optimization Manager',
    'Mobile Application Developer', 'Research Software Engineer',
    'Hardware Technician', 'Account Strategist', 'Technology Associate',
    'Senior Test Analyst', 'Principal Product Manager',
    'Software Development Vice President', 'Data Modeler',
    'Service Professional Manager', 'Associate Quality Analyst',
    'ETL Architect', 'Programmer Analyst Intern',
    'Senior Software Engineering Manager', 'Information Security Engineer',
    'Assistant Systems Analyst', 'Technical Marketing Engineer',
    'Service Desk Technician', 'Network Operation Center Analyst',
    'User Support Specialist', 'Network Engineer Intern',
    'Senior Business Intelligence Consultant', '3D Software Engineer',
    'Business Intelligence Lead', 'Advisor Information Technology Specialist',
    'Software Technician', 'JavaScript Developer', 'Application Developer II',
    'Implementation Project Manager', 'Technical Project Lead',
    'Quality Assurance Engineer Intern', 'Siebel Consultant',
    'Lead Systems Administrator', 'Computer Systems Analyst',
    'Information Security Intern', 'Senior SAP Technical Consultant',
    'Technical Support Engineer II', 'Software Development Head',
    'Software Project Engineer', 'GIS Developer',
    'Instrument Technician Help Desk Technician', 'Website Developer',
    'Desktop Analyst', 'Network Operation Center Engineer',
    'Senior Solution Architect', 'Senior Application Analyst',
    'PeopleSoft Developer', 'Performance Test Engineer', 'Linux Administrator',
    'UX Design Intern', 'Oracle Technical Consultant', 'Web Engineer',
    'Business Systems Consultant', 'Administrator III',
    'Quality Assurance Analyst II', 'Senior Technical Project Manager',
    'Staff Consultant', 'Senior User Experience Designer',
    'SharePoint Administrator', 'Software Associate',
    'Web Application Engineer', 'Network Security Analyst',
    'Data Warehouse Consultant', 'Computer Science Assistant Professor',
    'Interim Engineering Intern', 'Senior Support Technician',
    'Senior Help Desk Technician', 'Help Desk Lead',
    'Technical Support Specialist II', 'Associate Technical Architect',
    'Systems Engineer III', 'Information Technology Operation Manager',
    'Freelance Web Developer', 'Ab Initio Developer',
    'Instrument Technician Help Desk', 'Information Technology Analyst II',
    'Senior Web Designer', 'Help Desk Support Technician',
    'Information Security Officer', 'Senior User Interface Designer',
    'Application Development Intern', 'Associate Technical Account Manager',
    'Senior Front End Developer', 'Game Engineer', 'Advanced Systems Engineer',
    'PeopleSoft Technical Consultant', 'Associate Web Designer',
    'Junior Systems Analyst', 'Senior Unix Administrator',
    'Business Technology Analyst', 'Senior Technical Architect',
    'Unix Systems Engineer', 'Application Systems Analyst', 'Website Designer',
    'Interactive Project Manager', 'Business Systems Analyst Intern',
    'SAP Security Consultant', 'Senior Associate Programmer',
    'Information Technology Developer', 'Premier Field Engineer',
    'Customer Relationship Management Consultant', 'Integration Consultant',
    'Network Architect', 'Business Intelligence Engineer',
    'Trainee Software Developer', 'Functional Consultant',
    'Lead Programmer Analyst', 'Computer Systems Engineer',
    'Engagement Controller', 'Computer Engineering Intern',
    'Information Assurance Officer', 'Technical Staff Senior Member',
    'Java Developer Intern', 'Senior Network Specialist',
    'Quality Assurance Test Engineer',
    'Senior Business Intelligence Developer', 'Software Development Team Lead',
    'Software Development Supervisor', 'Junior .NET Developer',
    'Application Support Engineer', 'Tester', 'Business Systems Developer',
    'Senior Unix Systems Administrator', 'Computer Repair Technician',
    'Senior Functional Analyst', 'Associate Database Administrator',
    'Computer Support', 'Desktop Support Administrator',
    'Digital Business Analyst Consultant', 'Mid Market Account Executive',
    'Desktop Support Engineer', 'Development Student', 'Software Test Lead',
    'Associate Network Analyst', 'Advanced Business Analyst',
    'Help Desk Manager', 'Information Technology Team Lead',
    'Senior PHP Developer', 'Technical Staff Associate Member',
    'Technician Intern', 'Application Development Director',
    'Software Project Manager', 'Escalation Engineer', 'Freelance Web Designer',
    'Front End Developer Intern', 'Configuration Manager', 'Search Strategist',
    'Senior Executive Officer Strategist', 'Websphere Administrator',
    'Senior .NET Developer', 'Associate Support Engineer',
    'Senior Performance Engineer', 'Test Associate', 'Desktop Engineer',
    'Senior Technical Lead', 'Technical Team Lead', 'Lead Business Analyst',
    'Senior Software Quality Engineer', 'Senior Software Engineer II',
    'Senior Network Technician', 'Associate Security Consultant',
    'Server Engineer', 'Senior Systems Programmer', 'Systems Associate',
    'Junior Programmer Analyst',
    'Senior Geographic Information Systems Analyst', 'Lead Web Designer',
    'Senior Visual Designer', 'Web Development Manager',
    'Senior Software Development Manager', 'Game Developer',
    'Information Systems Engineer', 'User Experience Intern',
    'Assistant Programmer', 'Module Leader',
    'Senior Technical Support Specialist', 'Systems Intern',
    'Software Quality Assurance Lead', 'SAP Software Development Consultant',
    'Channel Account Manager', 'Business Objects Consultant', 'Oracle PL',
    'Security Architect', 'Release Manager', 'Lotus Notes Administrator',
    'Software Designer', 'Network Analyst II', 'Test Automation Engineer',
    'iOS Engineer', 'Network Intern', 'Technology Analyst Intern',
    'Design Verification Engineer', 'Online Marketing Analyst',
    'Voice Engineer', 'User Experience Manager', 'Junior Technical Recruiter',
    'Epic Consultant', 'Business Architect',
    'Information Technology Specialist Intern', 'Software Lead',
    'WebLogic Administrator', 'Systems Integrator', 'OBIEE Consultant',
    'Technical Member', 'Product Owner', 'Information Security Consultant',
    'Junior Business Systems Analyst', 'Staff Firmware Engineer',
    'SAP Human Resources Consultant', 'Integration Analyst',
    'Hyperion Consultant', 'Salesforce Consultant',
    'Information Security Manager', 'Service Professional Engineer',
    'Search Analyst', 'Software Engineering Lead', 'Infrastructure Analyst',
    'Front End Web Developer Intern', 'Practice Director',
    'User Experience Lead', 'Usability Engineer',
    'Systems Administrator Intern', 'Junior UX Designer', 'Cognos Consultant',
    'Analyst Consultant', 'Requirements Analyst', 'Inside Account Executive',
    'Technical Analyst II', 'SAP Developer', 'Software Quality Analyst',
    'Application Administrator', 'Site Reliability Engineer', 'EDI Analyst',
    'Principal Development Manager', 'Client Success Manager',
    'Principal Architect', 'ABAP Developer', 'Programming Analyst',
    'Systems Executive', 'Pre Sales Consultant', 'Junior Security Analyst',
    'Client Partner', 'SharePoint Architect',
    'Instrument Technician Advisor Intern', 'Internet Marketing Manager',
    'Counter Intelligence Agent', 'Test Coordinator', 'Delivery Lead',
    'Software Developer III', 'Support Consultant', 'Test Manager',
    'Test Consultant', 'Principal Application Engineer',
    'Bench Sales Recruiter', 'Citrix Engineer',
    'Information Technology Specialist II', 'SAS Consultant',
    'Instrument Technician Operation Analyst', 'Data Center Manager',
    'Support Engineer Intern', 'Knowledge Engineer', 'Pre Sales Manager',
    'Data Warehouse Engineer', 'Integration Specialist', 'Web Specialist',
    'BizTalk Consultant', 'User Experience Specialist', 'ABAP Consultant',
    'Partner Account Manager', 'Computer Consultant',
    'Instrument Technician Business Consultant', 'Security Analyst Intern',
    'SAP Business Analyst', 'Data Warehouse Analyst',
    'Application Analyst Intern', 'Infrastructure Project Manager',
    'Mobile Product Manager', 'Senior Test Lead', 'Service Delivery Lead',
    'Release Coordinator', 'SAP Project Lead', 'Creative Technologist',
    'Service Architect', 'Support Specialist II', 'Interface Designer',
    'Infrastructure Specialist', 'Algorithm Engineer',
    'Assistant Programmer Analyst', 'Data Center Engineer',
    'Network Engineering Manager', 'Engagement Leader', 'Application Support',
    'Integration Architect', 'Alliance Manager', 'Advisor Engineer',
    'Software Quality Assurance Manager', 'Conversion Analyst',
    'Information Technology Infrastructure Manager', 'Usability Intern',
    'Embedded Software Intern', 'Unix Engineer', 'Assistant Network Engineer',
    'WebMethods Consultant', 'BIOS Engineer', 'Implementation Consultant II',
    'EDI Consultant', 'ATG Consultant', 'Deployment Engineer',
    'Localization Project Manager', 'Firmware Engineer Intern', 'Pre Sales',
    'Windows Administrator', 'Technical Support Intern', 'Mobile Engineer',
    'UX Researcher', 'MicroStrategy Consultant',
    'Senior Software Quality Assurance', 'Consultant Programmer',
    'Information Designer', 'Agile Coach', 'Application Packager',
    'JDE Consultant', 'SAP Project Manager',
    'Instrument Technician Technical Manager', 'Business Intelligence Intern',
    'Talent Acquisition Executive', 'iOS Intern', 'Platform Engineer',
    'Technical Support Engineer III', 'Agile Project Manager',
    'User Experience Engineer', 'Web Operation Manager',
    'Middleware Administrator', 'Localization Engineer',
    'Information Technology Project Manager II', 'Tier II Technical Support',
    'Software Development Analyst', 'Senior Associate L1',
    'Web Project Manager', 'Systems Software Specialist II', 'Analytical Lead',
    'Technical Solution Representative III', 'Technical Support Analyst II',
    'Local Area Network Manager', 'Information Security',
    'Documentum Consultant', 'Solution Development Analyst',
    'Automation Analyst', 'Information Technology Technician II',
    'Partner Marketing Manager', 'SAP Human Capital Management Consultant',
    'Help Desk Analyst II', 'Application Engineer II',
    'Client Support Specialist II', 'Marketing Operation Analyst',
    'Testing Analyst', 'Computer Operation Coordinator',
    'Assistant Web Designer', 'Associate Software Engineer Intern',
    'Quality Assurance Analyst Intern', 'Information Assurance Analyst',
    'Windows Engineer', 'Application Analyst II', 'Software Project Lead',
    'Web Architect', 'Firmware Intern', 'Onsite Project Lead',
    'Android Engineer', 'Senior Business Intelligence', 'Network Security',
    'Industrial Technical Engineer Intern', 'Senior Security', 'Android Intern',
    'Senior Technical Support', 'Release Lead', 'Assistant Webmaster',
    'Junior Network Analyst', 'Incident Coordinator',
    'Junior Application Analyst', 'Practice Lead', 'Information Engineer',
    'Network Administrator Intern', 'Programmer III',
    'Business Intelligence Specialist', 'Embedded Engineer',
    'Computer Operator II', 'Web Analyst Intern', 'Java Architect',
    'Executive Architect', 'Security Engineer Intern', 'Computer Vision Intern',
    'UX Architect', 'Computer Technician II', 'Enterprise Sales Manager',
    'Partner Sales Manager', 'Consultant QA',
    'Instrument Technician Operation Specialist',
    'Embedded Software Developer', 'Senior Consultant II',
    'Assistant Database Administrator', 'Service Sales Manager',
    'Maximo Consultant', 'Knowledge Analyst', 'Oracle Retail Consultant',
    'SAP Recruiter', 'Junior Embedded Software Engineer',
    'Software Coordinator', 'Software Design Intern',
    'Channel Marketing Specialist', 'Sales Consulting Manager', 'Java Engineer',
    'Assistant Help Desk Manager', 'Technical Solution Consultant II',
    'Delivery Analyst', 'Computer Operator III', 'Delivery Project Executive',
    'Technical Relationship Manager', 'Citrix Consultant', 'Software Assistant',
    'Junior Test Engineer', 'Content Engineer',
    'Information Technology Support Intern', 'Network Administrator Assistant',
    'Consulting Practice Manager', 'Embedded Systems Intern',
    'Federal Account Manager', 'HRIS Consultant', 'Solution Principal',
    'Change Management Analyst', 'Problem Coordinator',
    'Instrument Technician Project Analyst', 'Technical Support Team Lead',
    'Instrument Technician Technical Specialist',
    'Junior Help Desk Technician', 'Collaboration Engineer',
    'Software Product Manager', 'Solution Intern', 'Business Systems Advisor',
    'Information Management Consultant', 'Search Engine Marketing Manager',
    'Datastage Consultant', 'Business Technology Analyst Intern',
    'Test Automation', 'Solution Engineering Manager', 'UX Manager',
    'Consultant Specialist', 'UX Engineer', 'Technical Developer',
    'Cloud Architect', 'Security Researcher', 'Managed Service Manager',
    'EDI Specialist', 'Interaction Design Lead', 'Technical Support Associate',
    'Developer III', 'Storage Consultant', 'VMware Engineer',
    'Application Designer', 'Product Architect', 'Backend Engineer',
    'JD Edwards Consultant', 'Basis Consultant', 'Test Specialist',
    'User Experience Consultant', 'Federal Sales Manager',
    'SharePoint Engineer', 'Technical Consultant II', 'LAN Engineer',
    'User Researcher', 'Unified Communication Engineer', 'Middleware Engineer',
    'LAN Analyst', 'Full Stack Engineer', 'Support Analyst II',
    'Customer Success Coordinator', 'Data Center Operation Manager',
    'Technology Solution Manager', 'UX Consultant', 'Webmaster Intern',
    'Database Intern', 'Technical Support Representative II',
    'Exchange Administrator', 'Front End Engineer Intern', 'Database Designer',
    'Experience Architect', 'Web Technologist', 'Front End Intern',
    'Analytics Engineer', 'Quality Assurance Test Lead',
    'Information Technologist', 'Helpdesk Engineer', 'Messaging Engineer',
    'Technology Consultant II', 'Big Data Engineer',
    'Instrument Technician Site Lead', 'Junior Software Developer Intern',
    'Implementation Service Manager', 'Assistant Network Technician',
    'Big Data Intern', 'Assistant Test Engineer', 'FICO Consultant',
    'Information Security Lead', 'Service Professional Lead', 'Web Consultant',
]

# ── Role assignment ───────────────────────────────────────────────────────────

_EXECUTIVE_KEYWORDS = re.compile(
    r'\b(chief|vice president|vp|director|head of|cto|cio|ceo|executive|'
    r'principal|partner|practice director|engineering senior director|'
    r'software development vice president|engineering vice president)\b',
    re.IGNORECASE,
)

_SENIOR_KEYWORDS = re.compile(
    r'\b(senior|lead|staff|architect|manager|supervisor|'
    r'team lead|technical lead|module lead|module leader|'
    r'technical leader|sr\.?)\b',
    re.IGNORECASE,
)

_ENTRY_KEYWORDS = re.compile(
    r'\b(intern|trainee|junior|jr\.?|assistant|student|graduate|'
    r'associate|beginner|apprentice|entry)\b',
    re.IGNORECASE,
)


def assign_role(title: str) -> str:
    """
    Map a job title to one of four seniority tiers:
      'executive', 'senior', 'mid', 'entry'
    """
    if _EXECUTIVE_KEYWORDS.search(title):
        return 'executive'
    if _SENIOR_KEYWORDS.search(title):
        return 'senior'
    if _ENTRY_KEYWORDS.search(title):
        return 'entry'
    return 'mid'


def get_role_mapping() -> dict[str, str]:
    """Return {job_title: role} for all titles in JOB_TITLES."""
    return {title: assign_role(title) for title in JOB_TITLES}


if __name__ == '__main__':
    mapping = get_role_mapping()
    from collections import Counter
    counts = Counter(mapping.values())
    print(f"Total titles : {len(mapping)}")
    print(f"executive    : {counts['executive']}")
    print(f"senior       : {counts['senior']}")
    print(f"mid          : {counts['mid']}")
    print(f"entry        : {counts['entry']}")
    print("\nSample mappings:")
    for title in list(JOB_TITLES)[:8]:
        print(f"  {title:<45} → {mapping[title]}")
