export const ROLES = [
  ".NET Consultant",".NET Developer","3D Software Engineer","ABAP Consultant","ABAP Developer",
  "ATG Consultant","Ab Initio Developer","Account Development Representative","Account Strategist",
  "Administrator III","Advanced Business Analyst","Advanced Programmer","Advanced Software Engineer",
  "Advanced Systems Engineer","Advisor Engineer","Advisor Information Technology Specialist",
  "Agile Coach","Agile Project Manager","Algorithm Engineer","Alliance Manager","Analyst Consultant",
  "Analytical Lead","Analytics Engineer","Android Developer","Android Engineer","Android Intern",
  "Application Administrator","Application Analyst","Application Analyst II","Application Analyst Intern",
  "Application Architect","Application Consultant","Application Designer","Application Developer",
  "Application Developer II","Application Developer Intern","Application Development Director",
  "Application Development Intern","Application Development Manager","Application Development Specialist",
  "Application Engineer II","Application Packager","Application Programmer","Application Sales Representative",
  "Application Support","Application Support Analyst","Application Support Engineer",
  "Application Support Specialist","Application Systems Analyst","Assistant Database Administrator",
  "Assistant Help Desk Manager","Assistant Network Administrator","Assistant Network Engineer",
  "Assistant Network Technician","Assistant Programmer","Assistant Programmer Analyst",
  "Assistant Software Engineer","Assistant Systems Administrator","Assistant Systems Analyst",
  "Assistant Systems Engineer","Assistant Systems Trainee Engineer","Assistant Test Engineer",
  "Assistant Web Designer","Assistant Webmaster","Associate Business Systems Analyst",
  "Associate Database Administrator","Associate Developer","Associate Information Technology Analyst",
  "Associate Network Analyst","Associate Network Engineer","Associate Programmer",
  "Associate Programmer Analyst","Associate Project Manager","Associate Quality Analyst",
  "Associate Quality Assurance Engineer","Associate Security Consultant","Associate Software Developer",
  "Associate Software Engineer","Associate Software Engineer Intern","Associate Support Engineer",
  "Associate Systems Administrator","Associate Systems Analyst","Associate Systems Engineer",
  "Associate Technical Account Manager","Associate Technical Architect","Associate Technical Consultant",
  "Associate Web Designer","Automation Analyst","BIOS Engineer","Backend Engineer","Basis Consultant",
  "Bench Sales Recruiter","Big Data Engineer","Big Data Intern","BizTalk Consultant","Build Engineer",
  "Business Analyst Consultant","Business Application Analyst","Business Architect",
  "Business Intelligence Architect","Business Intelligence Consultant","Business Intelligence Developer",
  "Business Intelligence Engineer","Business Intelligence Intern","Business Intelligence Lead",
  "Business Intelligence Specialist","Business Objects Consultant","Business Objects Developer",
  "Business Systems Advisor","Business Systems Analyst","Business Systems Analyst Intern",
  "Business Systems Consultant","Business Systems Developer","Business Technology Analyst",
  "Business Technology Analyst Intern","Change Management Analyst","Channel Account Manager",
  "Channel Marketing Specialist","Chief Architect","Chief Technology Officer","Citrix Consultant",
  "Citrix Engineer","Client Partner","Client Success Manager","Client Support Specialist II",
  "Cloud Architect","Cognos Consultant","Cognos Developer","Collaboration Engineer",
  "Computer Consultant","Computer Engineer","Computer Engineering Intern","Computer Operation Coordinator",
  "Computer Operator II","Computer Operator III","Computer Repair Technician",
  "Computer Science Assistant Professor","Computer Science Tutor","Computer Support",
  "Computer Support Specialist","Computer Support Technician","Computer Systems Analyst",
  "Computer Systems Engineer","Computer Technician","Computer Technician II","Computer Vision Intern",
  "Configuration Manager","Configuration Specialist","Consultant Developer","Consultant Programmer",
  "Consultant QA","Consultant Specialist","Consulting Practice Manager","Content Engineer",
  "Conversion Analyst","Counter Intelligence Agent","Creative Technologist","Customer Engineer",
  "Customer Relationship Management Consultant","Customer Success Coordinator","Customer Success Manager",
  "Customer Support Engineer","Data Architect","Data Center Engineer","Data Center Manager",
  "Data Center Operation Manager","Data Center Technician","Data Modeler","Data Science Fellow",
  "Data Science Intern","Data Scientist","Data Scientist Intern","Data Warehouse Analyst",
  "Data Warehouse Consultant","Data Warehouse Developer","Data Warehouse Engineer",
  "Database Administrator","Database Architect","Database Consultant","Database Designer",
  "Database Developer","Database Engineer","Database Intern","Database Programmer",
  "Datastage Consultant","Datastage Developer","Delivery Analyst","Delivery Consultant",
  "Delivery Lead","Delivery Manager","Delivery Project Executive","Deployment Engineer",
  "Deployment Technician","Design Verification Engineer","Desktop Administrator","Desktop Analyst",
  "Desktop Engineer","Desktop Support Administrator","Desktop Support Analyst","Desktop Support Engineer",
  "Desktop Support Specialist","Desktop Support Technician","Desktop Technician","DevOps Engineer",
  "Developer","Developer Analyst","Developer II","Developer III","Developer Intern",
  "Development Student","Digital Analyst","Digital Business Analyst","Digital Business Analyst Consultant",
  "Digital Project Manager","Documentum Consultant","Drupal Developer","EDI Analyst","EDI Consultant",
  "EDI Specialist","ERP Consultant","ETL Architect","ETL Consultant","ETL Developer",
  "Embedded Engineer","Embedded Software Developer","Embedded Software Engineer","Embedded Software Intern",
  "Embedded Systems Engineer","Embedded Systems Intern","Engagement Controller","Engagement Leader",
  "Engineering Senior Director","Engineering Vice President","Enterprise Account Executive",
  "Enterprise Account Manager","Enterprise Architect","Enterprise Sales Manager","Epic Consultant",
  "Escalation Engineer","Exchange Administrator","Executive Architect","Experience Architect",
  "FICO Consultant","Federal Account Manager","Federal Sales Manager","Firmware Engineer",
  "Firmware Engineer Intern","Firmware Intern","Flash Developer","Freelance Web Designer",
  "Freelance Web Developer","Front End Developer","Front End Developer Intern","Front End Engineer",
  "Front End Engineer Intern","Front End Intern","Front End Web Developer","Front End Web Developer Intern",
  "Full Stack Engineer","Full Stack Web Developer","Functional Analyst","Functional Consultant",
  "GIS Developer","Game Developer","Game Engineer","Game Programmer","Graduate Technical Intern",
  "HRIS Consultant","Hadoop Developer","Hardware Technician","Help Desk Administrator",
  "Help Desk Analyst","Help Desk Analyst II","Help Desk Lead","Help Desk Manager","Help Desk Specialist",
  "Help Desk Support","Help Desk Support Technician","Help Desk Technician","Helpdesk Engineer",
  "Hyperion Consultant","Implementation Analyst","Implementation Consultant","Implementation Consultant II",
  "Implementation Engineer","Implementation Project Manager","Implementation Service Manager",
  "Incident Coordinator","Industrial Technical Engineer","Industrial Technical Engineer Intern",
  "Informatics Developer","Information Architect","Information Assurance Analyst",
  "Information Assurance Officer","Information Business Technology Analyst","Information Designer",
  "Information Engineer","Information Management Consultant","Information Security",
  "Information Security Analyst","Information Security Consultant","Information Security Engineer",
  "Information Security Intern","Information Security Lead","Information Security Manager",
  "Information Security Officer","Information Systems Engineer","Information Systems Intern",
  "Information Systems Technician","Information Technologist","Information Technology Administrator",
  "Information Technology Analyst","Information Technology Analyst II","Information Technology Architect",
  "Information Technology Associate","Information Technology Consultant","Information Technology Developer",
  "Information Technology Infrastructure Manager","Information Technology Intern",
  "Information Technology Operation Manager","Information Technology Professional",
  "Information Technology Programmer","Information Technology Project Coordinator",
  "Information Technology Project Manager","Information Technology Project Manager II",
  "Information Technology Recruiter","Information Technology Specialist","Information Technology Specialist II",
  "Information Technology Specialist Intern","Information Technology Support",
  "Information Technology Support Analyst","Information Technology Support Intern",
  "Information Technology Support Specialist","Information Technology Support Technician",
  "Information Technology Systems Administrator","Information Technology Team Lead",
  "Information Technology Technician","Information Technology Technician II","Infrastructure Analyst",
  "Infrastructure Engineer","Infrastructure Project Manager","Infrastructure Specialist",
  "Inside Account Executive","Integration Analyst","Integration Architect","Integration Consultant",
  "Integration Specialist","Interaction Design Lead","Interaction Designer","Interactive Developer",
  "Interactive Project Manager","Interface Designer","Interim Engineering Intern","Intern Programmer",
  "Internet Marketing Manager","J2EE Consultant","J2EE Developer","JD Edwards Consultant",
  "JDE Consultant","Java Architect","Java Consultant","Java Developer","Java Developer Intern",
  "Java Engineer","Java Programmer","Java Software Engineer","JavaScript Developer",
  "Junior .NET Developer","Junior Application Analyst","Junior Business Systems Analyst",
  "Junior Database Administrator","Junior Developer","Junior Embedded Software Engineer",
  "Junior Front End Developer","Junior Help Desk Technician","Junior Java Developer",
  "Junior Network Administrator","Junior Network Analyst","Junior Network Engineer","Junior Programmer",
  "Junior Programmer Analyst","Junior Quality Assurance Analyst","Junior Quality Assurance Engineer",
  "Junior Security Analyst","Junior Software Developer","Junior Software Developer Intern",
  "Junior Software Engineer","Junior Systems Administrator","Junior Systems Analyst",
  "Junior Systems Engineer","Junior Technical Recruiter","Junior Test Engineer","Junior UX Designer",
  "Junior Web Designer","Junior Web Developer","Knowledge Analyst","Knowledge Engineer",
  "LAN Analyst","LAN Engineer","Lead Application Developer","Lead Architect","Lead Business Analyst",
  "Lead Developer","Lead Program Manager","Lead Programmer","Lead Programmer Analyst",
  "Lead Software Developer","Lead Software Engineer","Lead Systems Administrator","Lead Web Designer",
  "Lead Web Developer","Linux Administrator","Linux Systems Administrator",
  "Local Area Network Administrator","Local Area Network Manager","Localization Engineer",
  "Localization Project Manager","Lotus Notes Administrator","Mainframe Developer",
  "Major Account District Manager","Managed Service Manager","Marketing Operation Analyst",
  "Maximo Consultant","Messaging Engineer","MicroStrategy Consultant","Mid Market Account Executive",
  "Middleware Administrator","Middleware Engineer","Mobile Application Developer","Mobile Developer",
  "Mobile Engineer","Mobile Product Manager","Module Lead","Module Leader","Multimedia Developer",
  "Network Administrator","Network Administrator Assistant","Network Administrator Intern",
  "Network Analyst","Network Analyst II","Network Architect","Network Consultant","Network Engineer",
  "Network Engineer II","Network Engineer III","Network Engineer Intern","Network Engineering Manager",
  "Network Intern","Network Operation Center Analyst","Network Operation Center Engineer",
  "Network Operation Center Technician","Network Operation Engineer","Network Security",
  "Network Security Analyst","Network Security Engineer","Network Specialist","Network Support",
  "Network Support Engineer","Network Support Specialist","Network Support Technician",
  "Network Systems Administrator","Network Systems Engineer","Network Technician","OBIEE Consultant",
  "Online Marketing Analyst","Oracle Application Consultant","Oracle Application Developer",
  "Oracle Consultant","Oracle Database Administrator","Oracle Developer","Oracle PL",
  "Oracle Retail Consultant","Oracle Technical Consultant","PC Support Specialist","PC Support Technician",
  "PHP Developer","Partner Account Manager","Partner Marketing Manager","Partner Sales Manager",
  "PeopleSoft Consultant","PeopleSoft Developer","PeopleSoft Technical Consultant",
  "Performance Test Engineer","Platform Engineer","Practice Director","Practice Lead","Pre Sales",
  "Pre Sales Consultant","Pre Sales Engineer","Pre Sales Manager","Premier Field Engineer",
  "Principal Application Engineer","Principal Architect","Principal Development Head",
  "Principal Development Manager","Principal Product Manager","Principal Software Engineer",
  "Problem Coordinator","Product Architect","Product Management Director","Product Owner","Programmer",
  "Programmer Analyst","Programmer Analyst II","Programmer Analyst III","Programmer Analyst Intern",
  "Programmer II","Programmer III","Programmer Trainee Analyst","Programming Analyst",
  "Quality Assurance Analyst","Quality Assurance Analyst II","Quality Assurance Analyst Intern",
  "Quality Assurance Automation Engineer","Quality Assurance Consultant","Quality Assurance Engineer",
  "Quality Assurance Engineer II","Quality Assurance Engineer Intern","Quality Assurance Lead",
  "Quality Assurance Test Engineer","Quality Assurance Test Lead","Quality Assurance Tester",
  "Release Coordinator","Release Engineer","Release Lead","Release Manager","Reports Developer",
  "Requirements Analyst","Research Programmer","Research Software Engineer","SAP ABAP Consultant",
  "SAP BW Consultant","SAP Basis Administrator","SAP Basis Consultant","SAP Business Analyst",
  "SAP Business Intelligence Consultant","SAP Consultant","SAP Developer","SAP FICO Consultant",
  "SAP Human Capital Management Consultant","SAP Human Resources Consultant","SAP Project Lead",
  "SAP Project Manager","SAP Recruiter","SAP Security Consultant","SAP Software Development Consultant",
  "SAP Technical Consultant","SAS Consultant","SDET Intern","SQL Database Administrator",
  "SQL Developer","SQL Server Database Administrator","Sales Consulting Manager",
  "Salesforce Administrator","Salesforce Consultant","Salesforce Developer","Scientific Programmer",
  "Scrum Master","Search Analyst","Search Engine Marketing Manager","Search Engine Optimization Manager",
  "Search Engine Optimization Specialist","Search Strategist","Security Analyst","Security Analyst Intern",
  "Security Architect","Security Consultant","Security Engineer","Security Engineer Intern",
  "Security Researcher","Senior .NET Developer","Senior Application Analyst","Senior Application Developer",
  "Senior Application Engineer","Senior Associate L1","Senior Associate Programmer",
  "Senior Business Analyst","Senior Business Intelligence","Senior Business Intelligence Consultant",
  "Senior Business Intelligence Developer","Senior Business Systems Analyst","Senior Consultant II",
  "Senior Database Administrator","Senior Developer","Senior Development Head",
  "Senior Executive Officer Analyst","Senior Executive Officer Strategist","Senior Firmware Engineer",
  "Senior Front End Developer","Senior Functional Analyst",
  "Senior Geographic Information Systems Analyst","Senior Help Desk Technician",
  "Senior Interaction Designer","Senior J2EE Developer","Senior Java Developer",
  "Senior Network Administrator","Senior Network Analyst","Senior Network Engineer",
  "Senior Network Specialist","Senior Network Technician","Senior Oracle Database Administrator",
  "Senior PHP Developer","Senior Performance Engineer","Senior Principal Consultant","Senior Programmer",
  "Senior Programmer Analyst","Senior Quality Assurance Analyst","Senior Quality Assurance Engineer",
  "Senior Quality Assurance Tester","Senior SAP Technical Consultant",
  "Senior SQL Server Digital Business Analyst","Senior Security","Senior SharePoint Consultant",
  "Senior Software Analyst","Senior Software Architect","Senior Software Consultant",
  "Senior Software Design Engineer","Senior Software Developer","Senior Software Development Engineer",
  "Senior Software Development Manager","Senior Software Engineer","Senior Software Engineer II",
  "Senior Software Engineering Manager","Senior Software Programmer","Senior Software Quality Assurance",
  "Senior Software Quality Assurance Engineer","Senior Software Quality Engineer",
  "Senior Solution Architect","Senior Solution Consultant","Senior Staff Software Engineer",
  "Senior Support Engineer","Senior Support Technician","Senior Systems Administrator",
  "Senior Systems Analyst","Senior Systems Architect","Senior Systems Engineer",
  "Senior Systems Programmer","Senior Technical Analyst","Senior Technical Architect",
  "Senior Technical Associate","Senior Technical Consultant","Senior Technical Lead",
  "Senior Technical Project Manager","Senior Technical Support","Senior Technical Support Engineer",
  "Senior Technical Support Specialist","Senior Technical Writer","Senior Test Analyst",
  "Senior Test Engineer","Senior Test Lead","Senior Unix Administrator",
  "Senior Unix Systems Administrator","Senior User Experience Designer","Senior User Interface Designer",
  "Senior Visual Designer","Senior Web Application Developer","Senior Web Designer","Senior Web Developer",
  "Server Administrator","Server Engineer","Service Account Manager","Service Architect",
  "Service Delivery Lead","Service Delivery Manager","Service Desk Analyst","Service Desk Technician",
  "Service Professional Consultant","Service Professional Engineer","Service Professional Lead",
  "Service Professional Manager","Service Sales Manager","Setup Configuration Analyst",
  "SharePoint Administrator","SharePoint Architect","SharePoint Consultant","SharePoint Developer",
  "SharePoint Engineer","Siebel Consultant","Site Reliability Engineer","Software Analyst",
  "Software Application Engineer","Software Architect","Software Assistant","Software Associate",
  "Software Consultant","Software Coordinator","Software Design Engineer","Software Design Engineer II",
  "Software Design Intern","Software Designer","Software Developer","Software Developer II",
  "Software Developer III","Software Developer Intern","Software Development Analyst",
  "Software Development Engineer","Software Development Engineer II","Software Development Engineer Intern",
  "Software Development Head","Software Development Intern","Software Development Manager",
  "Software Development Supervisor","Software Development Team Lead","Software Development Vice President",
  "Software Engineer","Software Engineer II","Software Engineer III","Software Engineer Intern",
  "Software Engineering Associate","Software Engineering Intern","Software Engineering Lead",
  "Software Engineering Manager","Software Intern","Software Lead","Software Manager",
  "Software Product Manager","Software Project Engineer","Software Project Lead","Software Project Manager",
  "Software Quality Analyst","Software Quality Assurance Analyst","Software Quality Assurance Engineer",
  "Software Quality Assurance Intern","Software Quality Assurance Lead","Software Quality Assurance Manager",
  "Software Quality Assurance Tester","Software Quality Engineer","Software Specialist",
  "Software Support Engineer","Software Technician","Software Test Engineer","Software Test Lead",
  "Software Tester","Software Trainee","Solution Analyst","Solution Architect","Solution Consultant",
  "Solution Developer","Solution Development Analyst","Solution Engineer","Solution Engineering Manager",
  "Solution Intern","Solution Principal","Staff Consultant","Staff Firmware Engineer",
  "Staff Software Engineer","Storage Administrator","Storage Consultant","Storage Engineer",
  "Student Programmer","Support Analyst","Support Analyst II","Support Consultant","Support Engineer",
  "Support Engineer Intern","Support Specialist II","Systems Administrator","Systems Administrator II",
  "Systems Administrator Intern","Systems Analyst","Systems Analyst II","Systems Analyst III",
  "Systems Analyst Intern","Systems Architect","Systems Associate","Systems Consultant",
  "Systems Developer","Systems Engineer","Systems Engineer II","Systems Engineer III",
  "Systems Engineer Intern","Systems Executive","Systems Integration Analyst","Systems Integrator",
  "Systems Intern","Systems Programmer","Systems Software Engineer","Systems Software Specialist II",
  "Systems Support Analyst","Systems Support Engineer","Systems Support Specialist",
  "Systems Support Technician","Systems Trainee Engineer","Talent Acquisition Executive",
  "Technical Account Manager","Technical Analyst II","Technical Architect","Technical Associate",
  "Technical Consultant","Technical Consultant II","Technical Developer","Technical Genius",
  "Technical Lead","Technical Leader","Technical Marketing Engineer","Technical Member",
  "Technical Program Manager","Technical Project Lead","Technical Project Manager","Technical Recruiter",
  "Technical Relationship Manager","Technical Solution Consultant II","Technical Solution Representative III",
  "Technical Staff Associate Member","Technical Staff Member","Technical Staff Senior Member",
  "Technical Support Analyst","Technical Support Analyst II","Technical Support Associate",
  "Technical Support Associate Engineer","Technical Support Engineer","Technical Support Engineer II",
  "Technical Support Engineer III","Technical Support Intern","Technical Support Representative II",
  "Technical Support Specialist","Technical Support Specialist II","Technical Support Team Lead",
  "Technical Team Lead","Technician Intern","Technology Analyst","Technology Analyst Intern",
  "Technology Architect","Technology Associate","Technology Consultant","Technology Consultant II",
  "Technology Head","Technology Solution Manager","Technology Support Specialist","Test Analyst",
  "Test Associate","Test Automation","Test Automation Engineer","Test Consultant","Test Coordinator",
  "Test Lead","Test Manager","Test Software Developer","Test Software Development Engineer",
  "Test Specialist","Tester","Testing Analyst","Tier II Technical Support","Trainee Programmer",
  "Trainee Software Developer","Trainee Software Engineer","UX Architect","UX Consultant",
  "UX Design Intern","UX Designer","UX Engineer","UX Manager","UX Researcher",
  "Unified Communication Engineer","Unix Administrator","Unix Engineer","Unix Systems Administrator",
  "Unix Systems Engineer","Usability Engineer","Usability Intern","User Experience Architect",
  "User Experience Consultant","User Experience Design Intern","User Experience Designer",
  "User Experience Engineer","User Experience Intern","User Experience Lead","User Experience Manager",
  "User Experience Researcher","User Experience Specialist","User Interface Designer",
  "User Interface Developer","User Interface Engineer","User Researcher","User Support Specialist",
  "VMware Engineer","Visual Data Specialist","Voice Engineer","Web Analyst","Web Analyst Intern",
  "Web Application Developer","Web Application Engineer","Web Architect","Web Consultant",
  "Web Design Intern","Web Designer","Web Developer","Web Developer Intern","Web Development Intern",
  "Web Development Manager","Web Engineer","Web Operation Manager","Web Programmer","Web Project Manager",
  "Web Specialist","Web Technologist","WebLogic Administrator","WebMethods Consultant","Webmaster",
  "Webmaster Intern","Website Designer","Website Developer","Websphere Administrator",
  "Windows Administrator","Windows Engineer","Windows Systems Administrator",
  "iOS Developer","iOS Engineer","iOS Intern",
];